### ISSUE TITLE
Memory leak because of ConnectionActor ignores Terminated messages after sender used for reply

### ISSUE THREAD

**Issue by t3hnar** [EventStore/EventStore.JVM#32]

**Comment by t3hnar** [comment]
https://github.com/akka/akka/issues/17087

**Comment by t3hnar** [comment]
fixed in https://github.com/EventStore/EventStore.JVM/releases/tag/v2.0.2

**Comment by gfduszynski** [comment]
Thanks for excellent support ;) Situation is much better now, however I believe there is still a problem.
I've measured ~6 kB/s leak. Test run out of memory after about 30 minutes, which is a tremendous improvement. I've used Eclipse Memory Analyzer to get some insights on this situations and I've got 3 suspects out of which 1 makes sense:

    One instance of "akka.actor.RepointableActorRef" loaded by "sun.misc.Launcher$AppClassLoader     
    @ 0xff09faa0" occupies 1 581 528 (37,61%) bytes. The memory is accumulated in one instance  
    of "scala.collection.immutable.Vector" loaded by "sun.misc.Launcher$AppClassLoader @  
    0xff09faa0".

Raw JVM test does not show any tendencies to leak memory as of now.
Btw, I've changed project Scala version to 2.11.6.
